/* IMa2  2007-2011 Jody Hey, Rasmus Nielsen and Sang Chul Choi */
#include <stdio.h>
#include "imahelp.h"

void imaHelpPrint ()
{
        /* 01234567890123456789012345678901234567890123456789012345678901234567890123456789 */
  printf ("IMa2(1)                   Commands Commands Manual                     IMa2(1)\n"
"\n"
"NAME\n"
"   IMa2 -- Isolation with migration 2\n"
"\n"
"SYNOPSIS\n"
"   IMa2 [OPTION]\n"
"\n"
"DESCRIPTION\n"
"   This document explains how to use the IMa2 computer program. The program\n"
"   implements a method for generating posterior probabilities for complex\n"
"   demographic population genetic models. IMa2 works similarly to the older IMa\n"
"   program, with some important additions. IMa2 can handle data and implement a\n"
"   model for multiple populations (for numbers of sampled populations between one\n"
"   and ten) – not just two populations (as was the case with the original IM and\n"
"   IMa programs). The method for multiple populations is described in two papers\n"
"   (Hey 2010b, a).\n"
"\n"
"   Options:\n"
"      --individual [FILE]\n"
"         The text file contains a list of individual names for each\n"
"         population or each geographic location.\n"
"      -a [NUMBERS]\n"
"         Concatenated numbers are used for changing population assignment\n"
"         features including\n"
"         1 for population assignment\n"
"         2 for population admixture\n"
"         3 for island demographic model\n"
"      --findmeanassignment\n"
"         Find a mean assignment using an assignment file.\n"
"\n"
"   Tasks:\n"
"      -a1\n"
"         Population assignment\n"
"      --findmeanassignment -iima.asn -oima.asn.sum\n"
"         Find a mean assignment using the assignment file, ima.asn\n"
"         and print the mean assignment in the output file, ima.asn.sum\n"
"\n"
"   Files:\n"
"      Individual file\n"
"         Users can use population assignment without using an individual\n"
"         file. IMa2 will use an input file to figure out how many individuals\n"
"         are in the data. Each genotype can be named using upto 10\n"
"         characters. Spaces in a name are not allowed. The order of individuals\n"
"         in the assignment is determined in which they appear in the input\n"
"         file. When users want a different order of individuals, they can use\n"
"         option --individual [FILE] where [FILE] is the file name of\n"
"         individuals." 
"\n"
"AUTHOR\n"
"   Written by Jody Hey, Rasmus Nielsen and Sang Chul Choi\n"
"\n"
"REPORTING BUGS\n"
"   Report bugs to google group of Isolation with Migration\n"
"   at http://groups.google.com/group/isolation-with-migration\n"
"\n"
"COPYRIGHT\n"
"   Copyright (C) 2007- Jody Hey, Rasmus Nielsen, Sang Chul Choi\n"
"   See the source for copying conditions.\n"
"   There is NO warranty; not even for MERCHANTABILITY\n"
);
}
