//
//  alder_block_junction.c
//  alder-align
//
//  Created by Sang Chul Choi on 8/9/13.
//  Copyright (c) 2013 Sang Chul Choi. All rights reserved.
//
//  Generated by GSL
//  Execute at
//  $ gsl-1.16/b/block:
//  gcc -DHAVE_CONFIG_H -I. -I../../block -I.. -I../.. -g -O2 -MT init.lo -MD -MP -MF .deps/init.Tpo -E ../../block/init.c  -fno-common -DPIC -o init.c
//  gcc -DHAVE_CONFIG_H -I. -I../../block -I.. -I../.. -g -O2 -MT file.lo -MD -MP -MF .deps/file.Tpo -E ../../block/file.c  -fno-common -DPIC -o file.c
//  gcc -DHAVE_CONFIG_H -I. -I../../block -I.. -I../.. -g -O2 -MT block.lo -MD -MP -MF .deps/block.Tpo -E ../../block/block.c  -fno-common -DPIC -o block.c

#include <stdio.h>
#include "alder_block_junction.h"

alder_block_junction *
alder_block_junction_alloc (const size_t n)
{
    alder_block_junction * b;
    
    if (n == 0)
    {
        GSL_ERROR_VAL ("block length n must be positive integer", GSL_EINVAL, 0);
    }
    
    b = (alder_block_junction *) malloc (sizeof (alder_block_junction));
    
    if (b == 0)
    {
        GSL_ERROR_VAL ("failed to allocate space for block struct", GSL_ENOMEM, 0);
    }
    
    b->data = (alder_junction *) calloc (1, 1 * n * sizeof (alder_junction));
    
    if (b->data == 0)
    {
        free (b);
        GSL_ERROR_VAL ("failed to allocate space for block data", GSL_ENOMEM, 0);
    }
    
    b->size = n;
    
    return b;
}

alder_block_junction *
alder_block_junction_calloc (const size_t n)
{
    size_t i;
    
    alder_block_junction * b = alder_block_junction_alloc (n);
    
    if (b == 0)
        return 0;
    
    
    
    for (i = 0; i < 1 * n; i++)
    {
        b->data[i] = (alder_junction){
            .start = 0LLU,
            .gap   = 0LU,
            .strand= 0,
            .motif = 0,
            .annot = 0,
            .countUnique = 0LU,
            .countMultiple = 0LLU,
            .overhangLeft = 0U,
            .overhangRight = 0U
        };
    }
    
    return b;
}

void
alder_block_junction_free (alder_block_junction * b)
{
    if (!b) { return ; };
    free (b->data);
    free (b);
}

int
alder_block_junction_fread (FILE * stream, alder_block_junction * b)
{
    size_t n = b->size ;
    
    alder_junction * data = b->data ;
    
    size_t items = fread (data, 1 * sizeof (alder_junction), n, stream);
    
    if (items != n)
    {
        GSL_ERROR ("fread failed", GSL_EFAILED);
    }
    
    return 0;
}

int
alder_block_junction_fwrite (FILE * stream, const alder_block_junction * b)
{
    size_t n = b->size ;
    
    alder_junction * data = b->data ;
    
    size_t items = fwrite (data, 1 * sizeof (alder_junction), n, stream);
    
    if (items != n)
    {
        GSL_ERROR ("fwrite failed", GSL_EFAILED);
    }
    
    return 0;
}

int
alder_block_junction_raw_fread (FILE * stream, alder_junction * data,
                              const size_t n, const size_t stride)
{
    if (stride == 1)
    {
        size_t items = fread (data, 1 * sizeof (alder_junction), n, stream);
        
        if (items != n)
        {
            GSL_ERROR ("fread failed", GSL_EFAILED);
        }
    }
    else
    {
        size_t i;
        
        for (i = 0; i < n; i++)
        {
            size_t item = fread (data + 1 * i * stride,
                                 1 * sizeof (alder_junction), 1, stream);
            if (item != 1)
            {
                GSL_ERROR ("fread failed", GSL_EFAILED);
            }
        }
    }
    
    return GSL_SUCCESS;
}

int
alder_block_junction_raw_fwrite (FILE * stream, const alder_junction * data,
                               const size_t n, const size_t stride)
{
    
    if (stride == 1)
    {
        size_t items = fwrite (data, 1 * sizeof (alder_junction), n, stream);
        
        if (items != n)
        {
            GSL_ERROR ("fwrite failed", GSL_EFAILED);
        }
    }
    else
    {
        size_t i;
        
        for (i = 0; i < n; i++)
        {
            size_t item = fwrite (data + 1 * i * stride,
                                  1 * sizeof (alder_junction),
                                  1, stream);
            if (item != 1)
            {
                GSL_ERROR ("fwrite failed", GSL_EFAILED);
            }
        }
    }
    
    return GSL_SUCCESS;
}

int
alder_block_junction_fprintf (FILE * stream, const alder_block_junction * b, const char *format)
{
    size_t n = b->size ;
    
    alder_junction * data = b->data ;
    
    size_t i;
    
    for (i = 0; i < n; i++)
    {
        int k;
        int status;
        
        for (k = 0; k < 1; k++)
        {
            if (k > 0)
            {
                status = putc (' ', stream);
                
                if (status == (-1))
                {
                    GSL_ERROR ("putc failed", GSL_EFAILED);
                }
            }
            status = fprintf (stream,
                              format,
                              data[1 * i + k]);
            if (status < 0)
            {
                GSL_ERROR ("fprintf failed", GSL_EFAILED);
            }
        }
        
        status = putc ('\n', stream);
        if (status == (-1))
        {
            GSL_ERROR ("putc failed", GSL_EFAILED);
        }
    }
    
    return 0;
}

int
alder_block_junction_fscanf (FILE * stream, alder_block_junction * b)
{
    size_t n = b->size ;
    
    alder_junction * data = b->data ;
    
    size_t i;
    
    for (i = 0; i < n; i++)
    {
        int k;
        for (k = 0; k < 1; k++)
        {
            alder_junction tmp ;
            
            int status = fscanf (stream, "%s", &tmp) ;
            
            data [1 * i + k] = tmp;
            
            
            if (status != 1)
            {
                GSL_ERROR ("fscanf failed", GSL_EFAILED);
            }
        }
    }
    
    return GSL_SUCCESS;
}

int
alder_block_junction_raw_fprintf (FILE * stream,
                                const alder_junction * data,
                                const size_t n,
                                const size_t stride,
                                const char *format)
{
    size_t i;
    
    for (i = 0; i < n; i++)
    {
        int k;
        int status;
        
        for (k = 0; k < 1; k++)
        {
            if (k > 0)
            {
                status = putc (' ', stream);
                
                if (status == (-1))
                {
                    GSL_ERROR ("putc failed", GSL_EFAILED);
                }
            }
            status = fprintf (stream,
                              format,
                              data[1 * i * stride + k]);
            if (status < 0)
            {
                GSL_ERROR ("fprintf failed", GSL_EFAILED);
            }
        }
        
        status = putc ('\n', stream);
        
        if (status == (-1))
        {
            GSL_ERROR ("putc failed", GSL_EFAILED);
        }
    }
    
    return 0;
}

int
alder_block_junction_raw_fscanf (FILE * stream,
                               alder_junction * data,
                               const size_t n,
                               const size_t stride)
{
    size_t i;
    
    for (i = 0; i < n; i++)
    {
        int k;
        for (k = 0; k < 1; k++)
        {
            alder_junction tmp;
            
            int status = fscanf (stream, "%s", &tmp) ;
            
            data [1 * i * stride + k] = tmp;
            
            if (status != 1)
                GSL_ERROR ("fscanf failed", GSL_EFAILED);
        }
    }
    
    return GSL_SUCCESS;
}

size_t
alder_block_junction_size (const alder_block_junction * b)
{
    return b->size ;
}

alder_junction *
alder_block_junction_data (const alder_block_junction * b)
{
    return b->data ;
}
